name: Build My Notes

on:
  push:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  Build:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4

      - uses: YFHD-osu/XOPP-Compiler@main
        with:
          output_directory: "compiled-pdfs"
          font_url: "https://github.com/microsoft/cascadia-code/releases/download/v2407.24/CascadiaCode-2407.24.zip"

      - name: Deploy to Output Branch
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: "compiled-pdfs"
          
          publish_branch: "compiled-outputs"
          force_orphan: true

          commit_message: "Deploy compiled PDFs from ${{ github.sha }}"